import { parse } from "csv-parse";
import fs from "node:fs";
const { finished } = require("stream/promises");

const rawData = {
  results: {
    columns: [
      "docid",
      "name",
      "distance",
      "NewAddress",
      "lat",
      "lon",
      "paidStatus",
      "compRating",
      "verified",
      "rateThis",
      "mappointer",
      "opstring",
      "area",
      "opennow",
      "type",
      "VNumber",
      "totalReviews",
      "video",
      "city",
      "thumbnail",
      "totJdReviews",
      "favflag",
      "attr_data",
      "an",
      "shopfront",
      "ishotel",
      "vertical",
      "vertical_name",
      "discount_Offer",
      "vertical_data",
      "position_flag",
      "Jadoopic",
      "sharedt_url",
      "cancall",
      "wpnumber",
      "action_node",
      "idxno",
      "linefive",
      "newadd",
      "newaddcolor",
      "dimages",
      "viewchange",
      "photocnt",
      "pdg",
      "nameln",
      "NewAddressln",
      "address_flg",
      "ask_mobile",
      "hcatarr",
      "callalocation",
      "compRatingln",
      "catalog_flag",
      "jdpay",
      "ratecard",
      "ds",
      "inapp",
      "bd_params",
      "jtkr",
      "useshare",
      "weburl",
      "rev",
      "nwtaglin",
      "tag",
      "starhotel",
      "revarr",
      "offertag",
      "ratingtag",
      "resp_rate",
      "pincode",
      "guarantee",
      "event_data",
      "msg_pop",
      "scd",
      "loccity",
    ],
    data: [
      [
        "022PXX22.XX22.220423144643.B6K4",
        "Green Door",
        "",
        "Near Vijay Garden Kavesar",
        "19.260363",
        "72.971912",
        "1",
        "2.3",
        "1",
        1,
        "1",
        {
          status:
            '<span class="font14 fw400 els color339">Open</span> <span class="font14 fw400 color111"> until 10:00 pm</span>',
          timing: "10:00 am - 10:00 pm",
        },
        "Ghodbunder Road Kavesar",
        1,
        "Personal Loans, Loans",
        "09972573578",
        "3",
        "",
        "mumbai",
        "https://content.jdmagicbox.com/comp/def_content/business_loans/default-business-loans-2-250.jpg?clr=#403326",
        "3",
        0,
        {
          node1: "",
          node2: "",
          node3: [
            '<span class="font14 fw400 color111">18 Years in Business</span>',
            0,
            0,
          ],
          node1color: [],
        },
        {},
        0,
        0,
        [],
        "other",
        "",
        [],
        "",
        "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.220423144643.B6K4.jpg",
        "https://www.justdial.com/DT-431Z4RQCIGM",
        1,
        [],
        "",
        71,
        "",
        "",
        "",
        [
          "https://content.jdmagicbox.com/comp/def_content/business_loans/default-business-loans-2.jpg",
          "https://content.jdmagicbox.com/comp/def_content/business_loans/default-business-loans-1.jpg",
          "https://content.jdmagicbox.com/comp/def_content/business_loans/default-business-loans-2.jpg",
          "https://content.jdmagicbox.com/comp/def_content/business_loans/default-business-loans-1.jpg",
        ],
        [0, 0, 0],
        "4",
        "",
        "Green Door",
        "Near Vijay Garden Kavesar",
        1,
        0,
        {
          id: 10359572,
          nid: 10359572,
          name: "Personal Loans",
        },
        "qFGZSGSdaythoLP4%2B3TuaBh8qSMcU00sYtEodSSmB%2FQ%3D",
        "2.3",
        0,
        {
          img: "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
          redirection_url: "",
        },
        {},
        "0",
        1,
        {
          did: "022PXX22.XX22.220423144643.B6K4",
          cmp_params: {
            bcity: "Thane",
            barea: "Kavesar",
            bpncdbd: "400615",
            paidstatus: "1",
            misc: "24576",
            ask_mobile: 0,
          },
        },
        "%2FJPIWXFzZNmYMOFNb5TpFfGAaqBmWnfwNz73UvS0B7c%3D",
        0,
        "Mumbai/Green-Door-Near-Vijay-Garden-Kavesar/022PXX22-XX22-220423144643-B6K4_BZDET",
        "",
        ["Mortgage Loans", "Personal Loans"],
        [],
        "",
        [],
        {},
        [],
        {
          lead: "145",
          lead_resp: "1",
          avg_resp_time_sec: "",
          tformat: "",
          color: "#339D3A",
        },
        "400615",
        "",
        {
          cname: "Green Door",
          docid: "022PXX22.XX22.220423144643.B6K4",
          rating: "2.3",
          rating_cnt: "3",
          city: "Thane",
          dcity: "mumbai",
          area: "Kavesar",
          pin: "400615",
          ds: "0",
          pdg: "",
          paid: "1",
          jd_verified: "1",
          guarantee: "",
          trust: "0",
          verified: "0",
          pos: 71,
          tag: "",
          cta_name: "",
          call_cta: "3",
          deals: "",
          jd_cash: "",
          isb2b: "0",
          miscellaneous_flag: null,
          distance: "",
          core_distance: 8232.25,
          search_type: "P",
        },
        1,
        "431Z4RQCIGM",
        "Thane",
      ],
      [
        "022PXX22.XX22.200526220308.D4X1",
        "TS Finserv",
        "",
        "Near Balaji Sweets Kalyan West",
        "19.240499",
        "73.134753",
        "1",
        "4",
        "1",
        1,
        "1",
        {
          status:
            '<span class="font14 fw400 els color339">Open</span> <span class="font14 fw400 color111"> until 7:30 pm</span>',
          timing: "9:00 am - 7:30 pm",
        },
        "Rambaug Main Road Kalyan West",
        1,
        "Personal Loans, Loans",
        "09972319707",
        "15",
        "",
        "mumbai",
        "https://content.jdmagicbox.com/comp/mumbai/x1/022pxx22.xx22.200526220308.d4x1/catalogue/finance-mandi-kalyan-west-mumbai-personal-loans-pud45vrs26-250.jpg?clr=#273f27",
        "15",
        0,
        {
          node1: "",
          node2: "",
          node3: ["", 0, 0],
          node1color: [],
        },
        {},
        0,
        0,
        [],
        "other",
        "",
        [],
        "",
        "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.200526220308.D4X1.jpg",
        "https://www.justdial.com/DT-43ITVINNXQQ",
        1,
        [],
        "",
        72,
        "",
        "",
        "",
        [
          "https://content.jdmagicbox.com/comp/mumbai/x1/022pxx22.xx22.200526220308.d4x1/catalogue/finance-mandi-kalyan-west-mumbai-personal-loans-pud45vrs26.jpg",
          "https://content.jdmagicbox.com/comp/mumbai/x1/022pxx22.xx22.200526220308.d4x1/catalogue/finance-mandi-kalyan-west-mumbai-personal-loans-ugpldoeaim.jpg",
          "https://content.jdmagicbox.com/comp/mumbai/x1/022pxx22.xx22.200526220308.d4x1/catalogue/finance-mandi-kalyan-west-mumbai-personal-loans-3iat6jjq5o.jpg",
          "https://content.jdmagicbox.com/comp/mumbai/x1/022pxx22.xx22.200526220308.d4x1/catalogue/finance-mandi-kalyan-west-mumbai-personal-loans-o0d8rjx8tx.jpg",
        ],
        [0, 0, 0],
        "4",
        "",
        "TS Finserv",
        "Near Balaji Sweets Kalyan West",
        1,
        0,
        {
          id: 10302885,
          nid: 10302885,
          name: "Loans",
        },
        "vtvztjhjBFrw504IAMvGlQaarnJo1T%2BHoP4M5P12Bho%3D",
        "4",
        0,
        {
          img: "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
          redirection_url: "",
        },
        {},
        "0",
        1,
        {
          did: "022PXX22.XX22.200526220308.D4X1",
          cmp_params: {
            bcity: "Kalyan",
            barea: "Kalyan West",
            bpncdbd: "421301",
            paidstatus: "1",
            misc: "8589950980",
            ask_mobile: 0,
          },
        },
        "Vvs0FvvBIxHOcESFyZzYaDaJd8nSua6PjNtjUfHgv0w%3D",
        0,
        "Mumbai/TS-Finserv-Near-Balaji-Sweets-Kalyan-West/022PXX22-XX22-200526220308-D4X1_BZDET",
        "I really like the way these people help with loans. I got a loan from kotak and cashkumar called me every day to update on whats happening. Will recommend them to everyone. Full marks to the T S Finance team for getting balance transfer with kotak bank. i didnt know that old loans interest rates can be reduced but they informed me and help get all loans   fresh loan at a lower rate.",
        ["Business Loans", "Personal Loans"],
        [
          {
            tag_name: "Trending",
            bg_colour: "#5271dd",
            txt_colour: "#FFFFFF",
            tag_image:
              "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/trending.svg",
          },
        ],
        "",
        {
          name: "Javed Pasha",
          rating: "5.0",
          review_date: "2023-02-27 16:44:59",
        },
        {},
        [],
        {
          lead: "246",
          lead_resp: "232",
          avg_resp_time_sec: "",
          tformat: "",
          color: "#339D3A",
        },
        "421301",
        "",
        {
          cname: "TS Finserv",
          docid: "022PXX22.XX22.200526220308.D4X1",
          rating: "4",
          rating_cnt: "15",
          city: "Kalyan",
          dcity: "mumbai",
          area: "Kalyan West",
          pin: "421301",
          ds: "0",
          pdg: "",
          paid: "1",
          jd_verified: "1",
          guarantee: "",
          trust: "0",
          verified: "0",
          pos: 72,
          tag: "Trending",
          cta_name: "",
          call_cta: "3",
          deals: "",
          jd_cash: "",
          isb2b: "0",
          miscellaneous_flag: null,
          distance: "",
          core_distance: 8249.06,
          search_type: "P",
        },
        1,
        "43ITVINNXQQ",
        "Kalyan",
      ],
      [
        "022PXX22.XX22.180627121634.K6P2",
        "Shubh International",
        "",
        "Near Mira Bhayandar Road Mira Road East",
        "19.2784527778",
        "72.8786",
        "1",
        "4.9",
        "1",
        1,
        "1",
        {
          status:
            '<span class="font14 fw400 els color339">Open</span> <span class="font14 fw400 color111"> until 9:00 pm</span>',
          timing: "9:00 am - 9:00 pm",
        },
        "Pleasant Road Mira Road East",
        1,
        "Loans, Business Loans",
        "",
        "50",
        "",
        "Mumbai",
        "https://content.jdmagicbox.com/comp/thane/p2/022pxx22.xx22.180627121634.k6p2/catalogue/shubh-international-mira-road-thane-mortgage-loans-0c8d15sdl0-250.jpg?clr=#442d22",
        "50",
        0,
        {
          node1: "",
          node2: "",
          node3: [
            '<span class="font14 fw400 color111">9 Years in Business</span>',
            1,
            1,
          ],
          node1color: [],
        },
        {},
        0,
        0,
        [],
        "other",
        "",
        [],
        "",
        "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.180627121634.K6P2.jpg",
        "https://www.justdial.com/DT-43YM6Q622YE",
        1,
        [],
        "",
        73,
        "",
        "",
        "",
        [
          "https://content.jdmagicbox.com/comp/thane/p2/022pxx22.xx22.180627121634.k6p2/catalogue/shubh-international-mira-road-thane-mortgage-loans-0c8d15sdl0.jpg?clr=#442d22",
          "https://content.jdmagicbox.com/comp/mumbai/p2/022pxx22.xx22.180627121634.k6p2/catalogue/shubh-international-mira-road-thane-mortgage-loans-r20ws99ocm.jpg",
          "https://content.jdmagicbox.com/comp/mumbai/p2/022pxx22.xx22.180627121634.k6p2/catalogue/shubh-international-mira-road-thane-mortgage-loans-tkpsaqy82x.jpg",
          "https://content.jdmagicbox.com/comp/mumbai/p2/022pxx22.xx22.180627121634.k6p2/catalogue/shubh-international-mira-road-thane-mortgage-loans-9306him2br.jpg",
          "https://content.jdmagicbox.com/comp/mumbai/p2/022pxx22.xx22.180627121634.k6p2/catalogue/shubh-international-mira-road-thane-mortgage-loans-02lr00hwk1.jpg",
        ],
        [0, 0, 0],
        "12",
        "C",
        "Shubh International",
        "Near Mira Bhayandar Road Mira Road East",
        1,
        1,
        {
          id: 10062199,
          nid: 10062199,
          name: "Business Loans",
        },
        "jN9u0NDl1N1qSo9xri3yeNj7VjH54xEf6MtPxZXHSHc%3D",
        "4.9",
        0,
        {
          img: "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
          redirection_url: "",
        },
        {},
        "0",
        1,
        {
          did: "022PXX22.XX22.180627121634.K6P2",
          cmp_params: {
            bcity: "Thane",
            barea: "Mira Road East",
            bpncdbd: "401107",
            paidstatus: "1",
            misc: "8592214020",
            ask_mobile: 1,
          },
        },
        "iVHNjJYZbFYUb8Cv5nDD6yUJTVn5dsTGj5uvdPCwgs4%3D",
        0,
        "Mumbai/Shubh-International-Near-Mira-Bhayandar-Road-Mira-Road-East/022PXX22-XX22-180627121634-K6P2_BZDET",
        "Best Loan Consultancy ...THEY GIVE US QUICK RESPONSES AND BEST INTEREST FOR US.......AND THEY WILL DONT TAKE THE PROCESSING FEES WITH CLIENT...THEY ARE BEST CONSULTANCY IN LOAN.......THANK YOU FOR HELPING ME.....AND GIVE ME BEST INTEREST",
        ["Business Loans", "Home Loans"],
        [
          {
            tag_name: "Trending",
            bg_colour: "#5271dd",
            txt_colour: "#FFFFFF",
            tag_image:
              "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/trending.svg",
          },
        ],
        "",
        {
          name: "Shantaram Satoskar",
          rating: "5.0",
          review_date: "2022-01-27 17:35:15",
        },
        {},
        [],
        {
          lead: "10",
          lead_resp: "0",
          avg_resp_time_sec: "",
        },
        "401107",
        "",
        {
          cname: "Shubh International",
          docid: "022PXX22.XX22.180627121634.K6P2",
          rating: "4.9",
          rating_cnt: "50",
          city: "Thane",
          dcity: "Mumbai",
          area: "Mira Road East",
          pin: "401107",
          ds: "0",
          pdg: "C",
          paid: "1",
          jd_verified: "1",
          guarantee: "",
          trust: "1",
          verified: "1",
          pos: 73,
          tag: "Trending",
          cta_name: "",
          call_cta: "2",
          deals: "",
          jd_cash: "",
          isb2b: "0",
          miscellaneous_flag: null,
          distance: "",
          core_distance: 8222.7,
          search_type: "P",
        },
        1,
        "43YM6Q622YE",
        "Thane",
      ],
      [
        "022PXX22.XX22.120706183613.Y3S8",
        "Mudrakosh",
        "",
        "Behind Byke Delote Borivali West",
        "19.230466",
        "72.85287",
        "1",
        "3.7",
        "1",
        1,
        "0",
        {
          status:
            '<span class="font14 fw400 els color339">Open</span> <span class="font14 fw400 color111"> until 9:00 pm</span>',
          timing: "9:30 am - 9:00 pm",
        },
        "Chandarvarkar Lane Borivali West",
        1,
        "Personal Loans, Loans",
        "07487013152",
        "15",
        "",
        "Mumbai",
        "https://content.jdmagicbox.com/def_content/personal_loans/default-personal-loans-8-250.jpg?clr=#808080",
        "15",
        0,
        {
          node1: "",
          node2: "",
          node3: [
            '<span class="font14 fw400 color111">10 Years in Business</span>',
            0,
            0,
          ],
          node1color: [],
        },
        {},
        0,
        0,
        [],
        "other",
        "",
        [],
        "",
        "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.120706183613.Y3S8.jpg",
        "https://www.justdial.com/DT-43XL97YP",
        1,
        [],
        "",
        74,
        "",
        "",
        "",
        [
          "https://content.jdmagicbox.com/def_content/personal_loans/default-personal-loans-8.jpg",
        ],
        [0, 0, 0],
        "1",
        "",
        "Mudrakosh",
        "Behind Byke Delote Borivali West",
        1,
        0,
        {
          id: 10028109,
          nid: 10028109,
          name: "Automobile Loans",
        },
        "oIdLf2WJYi4d3R9hYrLbTZEAGrbhHjhOnlzO1RdGvvo%3D",
        "3.7",
        0,
        {
          img: "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
          redirection_url: "",
        },
        {},
        "0",
        1,
        {
          did: "022PXX22.XX22.120706183613.Y3S8",
          cmp_params: {
            bcity: "Mumbai",
            barea: "Borivali West",
            bpncdbd: "400092",
            paidstatus: "1",
            misc: "24580",
            ask_mobile: 0,
          },
        },
        "K9gF8ogYz7%2FF5tJEpImY1qJ%2BzRCn3%2BB6CpVbfbEzyRc%3D",
        0,
        "Mumbai/Mudrakosh-Behind-Byke-Delote-Borivali-West/022PXX22-XX22-120706183613-Y3S8_BZDET",
        "",
        ["Mortgage Loans", "Personal Loans"],
        [
          {
            tag_name: "Trending",
            bg_colour: "#5271dd",
            txt_colour: "#FFFFFF",
            tag_image:
              "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/trending.svg",
          },
        ],
        "",
        [],
        {},
        [],
        {
          lead: "471",
          lead_resp: "8",
          avg_resp_time_sec: "",
          tformat: "",
          color: "#339D3A",
        },
        "400092",
        "",
        {
          cname: "Mudrakosh",
          docid: "022PXX22.XX22.120706183613.Y3S8",
          rating: "3.7",
          rating_cnt: "15",
          city: "Mumbai",
          dcity: "Mumbai",
          area: "Borivali West",
          pin: "400092",
          ds: "0",
          pdg: "",
          paid: "1",
          jd_verified: "1",
          guarantee: "",
          trust: "0",
          verified: "0",
          pos: 74,
          tag: "Trending",
          cta_name: "",
          call_cta: "3",
          deals: "",
          jd_cash: "",
          isb2b: "0",
          miscellaneous_flag: null,
          distance: "",
          core_distance: 8219.47,
          search_type: "P",
        },
        1,
        "43XL97YP",
        "Mumbai",
      ],
      [
        "022PXX22.XX22.130214133028.K4I8",
        "Unique Finmart",
        "",
        "Near Juhi Green Tower Seawoods",
        "19.0106269",
        "73.016816",
        "1",
        "4.6",
        "1",
        1,
        "1",
        {
          status:
            '<span class="font14 fw400 els color339">Open</span> <span class="font14 fw400 color111"> until 9:30 pm</span>',
          timing: "9:30 am - 9:30 pm",
        },
        "Sector-50 Old Seawoods",
        1,
        "Personal Loans, Loans",
        "",
        "28",
        "",
        "Mumbai",
        "https://content.jdmagicbox.com/comp/mumbai/i8/022pxx22.xx22.130214133028.k4i8/catalogue/unique-finmart-seawoods-mumbai-personal-loans-4z2gjs7top-250.jpg?clr=#665200",
        "28",
        0,
        {
          node1: "",
          node2: "",
          node3: [
            '<span class="font14 fw400 color111">21 Years in Business</span>',
            0,
            0,
          ],
          node1color: [],
        },
        {},
        0,
        0,
        [],
        "other",
        "",
        [],
        "",
        "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.130214133028.K4I8.jpg",
        "https://www.justdial.com/DT-434PJNF4",
        1,
        [],
        "",
        75,
        "",
        "",
        "",
        [
          "https://content.jdmagicbox.com/comp/mumbai/i8/022pxx22.xx22.130214133028.k4i8/catalogue/unique-finmart-seawoods-mumbai-personal-loans-4z2gjs7top.jpg?clr=#665200",
          "https://content.jdmagicbox.com/comp/navi-mumbai/i8/022pxx22.xx22.130214133028.k4i8/catalogue/unique-finmart-seawoods-navi-mumbai-business-loans-qrwcc4b0zs.jpg",
          "https://content.jdmagicbox.com/comp/navi-mumbai/i8/022pxx22.xx22.130214133028.k4i8/catalogue/unique-finmart-seawoods-navi-mumbai-business-loans-dx0fh444dh.jpg",
          "https://content.jdmagicbox.com/comp/navi-mumbai/i8/022pxx22.xx22.130214133028.k4i8/catalogue/unique-finmart-seawoods-navi-mumbai-business-loans-ym8ar0bjxk.jpg",
          "https://content.jdmagicbox.com/comp/navi-mumbai/i8/022pxx22.xx22.130214133028.k4i8/catalogue/unique-finmart-seawoods-navi-mumbai-business-loans-folfwhg0r7.jpg",
        ],
        [0, 0, 0],
        "19",
        "V",
        "Unique Finmart",
        "Near Juhi Green Tower Seawoods",
        1,
        1,
        {
          id: 10062199,
          nid: 10062199,
          name: "Business Loans",
        },
        "UQqY00Qr9ZND6HuH3XgyKQHV7%2BO7kHEQ9g5G2ogCMNw%3D",
        "4.6",
        0,
        {
          img: "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
          redirection_url: "",
        },
        {},
        "0",
        1,
        {
          did: "022PXX22.XX22.130214133028.K4I8",
          cmp_params: {
            bcity: "Navi Mumbai",
            barea: "Seawoods",
            bpncdbd: "400706",
            paidstatus: "1",
            misc: "2113536",
            ask_mobile: 1,
          },
        },
        "aWgnQ8OyJoAmauaxXM1mw%2Fnro7DNHg%2BHOh%2FhmHen7hs%3D",
        0,
        "Mumbai/Unique-Finmart-Near-Juhi-Green-Tower-Seawoods/022PXX22-XX22-130214133028-K4I8_BZDET",
        "Unique Finmart is an ideal place for home loan seeker. It helps me to get home loan at very reasonable rate and very quickly. Also it meets my maximum expected loan amount. Good people to deal with. ",
        ["Home Loans", "Business Loans"],
        [
          {
            tag_name: "Trending",
            bg_colour: "#5271dd",
            txt_colour: "#FFFFFF",
            tag_image:
              "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/trending.svg",
          },
        ],
        "",
        {
          name: "Amit More",
          rating: "4.5",
          review_date: "2018-04-19 18:28:49",
        },
        {},
        [],
        {
          lead: "13",
          lead_resp: "0",
          avg_resp_time_sec: "",
        },
        "400706",
        "",
        {
          cname: "Unique Finmart",
          docid: "022PXX22.XX22.130214133028.K4I8",
          rating: "4.6",
          rating_cnt: "28",
          city: "Navi Mumbai",
          dcity: "Mumbai",
          area: "Seawoods",
          pin: "400706",
          ds: "0",
          pdg: "V",
          paid: "1",
          jd_verified: "1",
          guarantee: "",
          trust: "0",
          verified: "0",
          pos: 75,
          tag: "Trending",
          cta_name: "",
          call_cta: "2",
          deals: "",
          jd_cash: "",
          isb2b: "0",
          miscellaneous_flag: null,
          distance: "",
          core_distance: 8234.18,
          search_type: "P",
        },
        1,
        "434PJNF4",
        "Navi Mumbai",
      ],
      [
        "022PXX22.XX22.161109112749.H5P2",
        "Simran Business Loan",
        "",
        "Old Kapol Bank Vile Parle West",
        "19.117878",
        "72.848092",
        "1",
        "3.7",
        "1",
        1,
        "1",
        {
          status:
            '<span class="font14 fw400 els color339">Open</span> <span class="font14 fw400 color111"> until 7:00 pm</span>',
          timing: "10:00 am - 7:00 pm",
        },
        "Prabhu Deshpande Vile Parle West",
        1,
        "Personal Loans, Loans",
        "09845446342",
        "9",
        "",
        "Mumbai",
        "https://content.jdmagicbox.com/comp/def_content/business_loans/default-business-loans-0-250.jpg?clr=#29293d",
        "9",
        0,
        {
          node1: "",
          node2: "",
          node3: [
            '<span class="font14 fw400 color111">11 Years in Business</span>',
            0,
            0,
          ],
          node1color: [],
        },
        {},
        0,
        0,
        [],
        "other",
        "",
        [],
        "",
        "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.161109112749.H5P2.jpg",
        "https://www.justdial.com/DT-43EUI2U22QU",
        1,
        [],
        "",
        76,
        "",
        "",
        "",
        [
          "https://content.jdmagicbox.com/comp/def_content/business_loans/default-business-loans-0.jpg",
          "https://content.jdmagicbox.com/comp/def_content/business_loans/default-business-loans-1.jpg",
          "https://content.jdmagicbox.com/comp/def_content/business_loans/default-business-loans-2.jpg",
          "https://content.jdmagicbox.com/comp/def_content/business_loans/default-business-loans-3.jpg",
        ],
        [0, 0, 0],
        "39",
        "",
        "Simran Business Loan",
        "Old Kapol Bank Vile Parle West",
        1,
        0,
        {
          id: 10062199,
          nid: 10062199,
          name: "Business Loans",
        },
        "G9ev1q1mGX9i2LO44sH0kDfln%2BE7U3b2vObLr1kF2pM%3D",
        "3.7",
        0,
        {
          img: "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
          redirection_url: "",
        },
        {},
        "0",
        1,
        {
          did: "022PXX22.XX22.161109112749.H5P2",
          cmp_params: {
            bcity: "Mumbai",
            barea: "Vile Parle West",
            bpncdbd: "400056",
            paidstatus: "1",
            misc: "8589959172",
            ask_mobile: 0,
          },
        },
        "3yV4EBQoV6jcEru6v89ObA6OCFktJe7fsylDEBU%2BweY%3D",
        0,
        "Mumbai/Simran-Business-Loan-Old-Kapol-Bank-Vile-Parle-West/022PXX22-XX22-161109112749-H5P2_BZDET",
        "",
        ["Business Loans", "Home Loans"],
        [
          {
            tag_name: "Trending",
            bg_colour: "#5271dd",
            txt_colour: "#FFFFFF",
            tag_image:
              "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/trending.svg",
          },
        ],
        "",
        [],
        {},
        [],
        {
          lead: "262",
          lead_resp: "2",
          avg_resp_time_sec: "",
          tformat: "",
          color: "#339D3A",
        },
        "400056",
        "",
        {
          cname: "Simran Business Loan",
          docid: "022PXX22.XX22.161109112749.H5P2",
          rating: "3.7",
          rating_cnt: "9",
          city: "Mumbai",
          dcity: "Mumbai",
          area: "Vile Parle West",
          pin: "400056",
          ds: "0",
          pdg: "",
          paid: "1",
          jd_verified: "1",
          guarantee: "",
          trust: "0",
          verified: "0",
          pos: 76,
          tag: "Trending",
          cta_name: "",
          call_cta: "3",
          deals: "",
          jd_cash: "",
          isb2b: "0",
          miscellaneous_flag: null,
          distance: "",
          core_distance: 8217.7,
          search_type: "P",
        },
        1,
        "43EUI2U22QU",
        "Mumbai",
      ],
      [
        "022PXX22.XX22.230121021513.Q8L2",
        "Ace Financial Solutions",
        "",
        "Opp Jain Mandir and Behind Jain Cosmos Bnk Vasai West",
        "19.383588402778",
        "72.828039520504",
        "1",
        "4.3",
        "1",
        1,
        "1",
        {
          status:
            '<span class="font14 fw400 els color339">Open</span> <span class="font14 fw400 color111"> until 6:00 pm</span>',
          timing: "10:00 am - 6:00 pm",
        },
        "Ambadi Road Vasai West",
        1,
        "Personal Loans, Loans",
        "09972904967",
        "8",
        "",
        "mumbai",
        "https://content.jdmagicbox.com/comp/mumbai/l2/022pxx22.xx22.230121021513.q8l2/catalogue/ace-financial-solutions-mumbai-finance-consultants-gc0urcrrbw-250.jpg",
        "8",
        0,
        {
          node1: "",
          node2: "",
          node3: [
            '<span class="font14 fw400 color111">3 Years in Business</span>',
            1,
            0,
          ],
          node1color: [],
        },
        {},
        0,
        0,
        [],
        "other",
        "",
        [],
        "",
        "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.230121021513.Q8L2.jpg",
        "https://www.justdial.com/DT-43BRRXXIFPH",
        1,
        [],
        "",
        77,
        "",
        "",
        "",
        [
          "https://content.jdmagicbox.com/comp/mumbai/l2/022pxx22.xx22.230121021513.q8l2/catalogue/ace-financial-solutions-mumbai-finance-consultants-gc0urcrrbw.jpg",
          "https://content.jdmagicbox.com/comp/mumbai/l2/022pxx22.xx22.230121021513.q8l2/catalogue/ace-financial-solutions-vasai-west-palghar-finance-consultants-dkrpr433gb.jpg",
        ],
        [0, 0, 0],
        "2",
        "",
        "Ace Financial Solutions",
        "Opp Jain Mandir and Behind Jain Cosmos Bnk Vasai West",
        1,
        0,
        {
          id: 10206621,
          nid: 10206621,
          name: "Finance Consultants",
        },
        "ugf9qLPLUneA8fkNqxxRzxCmXjvAY3oxN%2B0yiXRT034%3D",
        "4.3",
        0,
        {
          img: "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
          redirection_url: "",
        },
        {},
        "0",
        1,
        {
          did: "022PXX22.XX22.230121021513.Q8L2",
          cmp_params: {
            bcity: "Palghar",
            barea: "Vasai West",
            bpncdbd: "401202",
            paidstatus: "1",
            misc: "24576",
            ask_mobile: 0,
          },
        },
        "pfSD9ajS0RUhu6BWcs7Q2gwFJJ6yo43EyxohZySDzVg%3D",
        0,
        "Mumbai/Ace-Financial-Solutions-Opp-Jain-Mandir-and-Behind-Jain-Cosmos-Bnk-Vasai-West/022PXX22-XX22-230121021513-Q8L2_BZDET",
        "I have got flexible and good options of banks and their rules With authenticated panel of guide persons.\r\nGood service.",
        ["Personal Loans", "Business Loans"],
        [
          {
            tag_name: "Trending",
            bg_colour: "#5271dd",
            txt_colour: "#FFFFFF",
            tag_image:
              "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/trending.svg",
          },
        ],
        "",
        {
          name: "Alka",
          rating: "4.0",
          review_date: "2023-04-07 13:17:25",
        },
        {},
        [],
        {
          lead: "183",
          lead_resp: "8",
          avg_resp_time_sec: "",
          tformat: "",
          color: "#339D3A",
        },
        "401202",
        "",
        {
          cname: "Ace Financial Solutions",
          docid: "022PXX22.XX22.230121021513.Q8L2",
          rating: "4.3",
          rating_cnt: "8",
          city: "Palghar",
          dcity: "mumbai",
          area: "Vasai West",
          pin: "401202",
          ds: "0",
          pdg: "",
          paid: "1",
          jd_verified: "1",
          guarantee: "",
          trust: "0",
          verified: "1",
          pos: 77,
          tag: "Trending",
          cta_name: "",
          call_cta: "3",
          deals: "",
          jd_cash: "",
          isb2b: "0",
          miscellaneous_flag: null,
          distance: "",
          core_distance: 8218.6,
          search_type: "P",
        },
        1,
        "43BRRXXIFPH",
        "Palghar",
      ],
      [
        "022PXX22.XX22.200915124306.J4W4",
        "Mangal Credit And Fincorp Ltd",
        "",
        "Off Western Express Highway Goregaon East",
        "19.145318",
        "72.853981",
        "1",
        "4.5",
        "1",
        1,
        "1",
        {
          status:
            '<span class="font14 fw400 els color339">Open</span> <span class="font14 fw400 color111"> until 6:00 pm</span>',
          timing: "8:00 am - 6:00 pm",
        },
        "Ram Mandir Road Goregaon East",
        1,
        "Personal Loans, Loans",
        "",
        "81",
        "",
        "mumbai",
        "https://content.jdmagicbox.com/comp/mumbai/w4/022pxx22.xx22.200915124306.j4w4/catalogue/mangal-credit-and-fincorp-ltd-goregaon-east-mumbai-personal-loans-b9deegbvy6-250.jpg?clr=#4f3317",
        "81",
        0,
        {
          node1: "",
          node2: "",
          node3: [
            '<span class="font14 fw400 color111">14 Years in Business</span>',
            1,
            1,
          ],
          node1color: [],
        },
        {},
        0,
        0,
        [],
        "other",
        "",
        [],
        "",
        "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.200915124306.J4W4.jpg",
        "https://www.justdial.com/DT-43VZ3XM5F2B",
        1,
        [],
        "",
        78,
        "",
        "",
        "",
        [
          "https://content.jdmagicbox.com/comp/mumbai/w4/022pxx22.xx22.200915124306.j4w4/catalogue/mangal-credit-and-fincorp-ltd-goregaon-east-mumbai-personal-loans-b9deegbvy6.jpg?clr=#4f3317",
          "https://content.jdmagicbox.com/comp/mumbai/w4/022pxx22.xx22.200915124306.j4w4/catalogue/mangal-credit-and-fincorp-ltd-goregaon-east-mumbai-home-loans-rgu0169v5y.jpg",
          "https://content.jdmagicbox.com/comp/mumbai/w4/022pxx22.xx22.200915124306.j4w4/catalogue/mangal-credit-and-fincorp-ltd-goregaon-east-mumbai-home-loans-nyiatfa4q1.jpg",
          "https://content.jdmagicbox.com/comp/mumbai/w4/022pxx22.xx22.200915124306.j4w4/catalogue/mangal-credit-and-fincorp-ltd-goregaon-east-mumbai-home-loans-z7h2yonwky.jpg",
          "https://content.jdmagicbox.com/comp/mumbai/w4/022pxx22.xx22.200915124306.j4w4/catalogue/mangal-credit-and-fincorp-ltd-goregaon-east-mumbai-home-loans-ia8r3atu16.jpg",
        ],
        [0, 0, 0],
        "19",
        "V",
        "Mangal Credit And Fincorp Ltd",
        "Off Western Express Highway Goregaon East",
        1,
        1,
        {
          id: 10250496,
          nid: 10250496,
          name: "Home Loans",
        },
        "vtvztjhjBFrw504IAMvGlclBmU6%2BJsiAWGP75WOlirI%3D",
        "4.5",
        0,
        {
          img: "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
          redirection_url: "",
        },
        {},
        "0",
        1,
        {
          did: "022PXX22.XX22.200915124306.J4W4",
          cmp_params: {
            bcity: "Mumbai",
            barea: "Goregaon East",
            bpncdbd: "400063",
            paidstatus: "1",
            misc: "2125828",
            ask_mobile: 1,
          },
        },
        "ssQH%2FgdeCWo3WRQBZ4w42%2BnCpismYGcnbQaAj5n1ruw%3D",
        0,
        "Mumbai/Mangal-Credit-And-Fincorp-Ltd-Off-Western-Express-Highway-Goregaon-East/022PXX22-XX22-200915124306-J4W4_BZDET",
        "",
        ["Home Loans", "Mortgage Loans"],
        [
          {
            tag_name: "Trending",
            bg_colour: "#5271dd",
            txt_colour: "#FFFFFF",
            tag_image:
              "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/trending.svg",
          },
        ],
        "",
        [],
        {},
        [],
        {
          lead: "111",
          lead_resp: "0",
          avg_resp_time_sec: "",
        },
        "400063",
        "",
        {
          cname: "Mangal Credit And Fincorp Ltd",
          docid: "022PXX22.XX22.200915124306.J4W4",
          rating: "4.5",
          rating_cnt: "81",
          city: "Mumbai",
          dcity: "mumbai",
          area: "Goregaon East",
          pin: "400063",
          ds: "0",
          pdg: "V",
          paid: "1",
          jd_verified: "1",
          guarantee: "",
          trust: "1",
          verified: "1",
          pos: 78,
          tag: "Trending",
          cta_name: "",
          call_cta: "2",
          deals: "",
          jd_cash: "",
          isb2b: "0",
          miscellaneous_flag: null,
          distance: "",
          core_distance: 8218.63,
          search_type: "P",
        },
        1,
        "43VZ3XM5F2B",
        "Mumbai",
      ],
      [
        "022PXX22.XX22.190118195026.M7Y1",
        "Turquoise Advisory",
        "",
        "Near Vishal Hall Andheri East",
        "19.1184082",
        "72.8523907",
        "1",
        "4.8",
        "1",
        1,
        "1",
        {
          status: '<span class="font14 fw400 color339">Open 24 Hrs</span>',
          timing: "Open 24 Hrs",
        },
        "Andheri Kurla Road Andheri East",
        1,
        "Loans, Business Loans",
        "",
        "3",
        "",
        "mumbai",
        "https://content.jdmagicbox.com/comp/mumbai/y1/022pxx22.xx22.190118195026.m7y1/catalogue/turquoise-advisory-andheri-east-mumbai-home-loans-qfzix0i5q4-250.jpg?clr=#000066",
        "3",
        0,
        {
          node1: "",
          node2: "",
          node3: ["", 0, 0],
          node1color: [],
        },
        {},
        0,
        0,
        [],
        "other",
        "",
        [],
        "",
        "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.190118195026.M7Y1.jpg",
        "https://www.justdial.com/DT-43U66I6YMU2",
        1,
        [],
        "",
        79,
        "",
        "",
        "",
        [
          "https://content.jdmagicbox.com/comp/mumbai/y1/022pxx22.xx22.190118195026.m7y1/catalogue/turquoise-advisory-andheri-east-mumbai-home-loans-qfzix0i5q4.jpg?clr=#000066",
        ],
        [0, 0, 0],
        "1",
        "V",
        "Turquoise Advisory",
        "Near Vishal Hall Andheri East",
        1,
        1,
        {
          id: 10062199,
          nid: 10062199,
          name: "Business Loans",
        },
        "JnqNX9JkIkhRdzNJp3aBxo1H4ShYigp4tLkspyi8wlY%3D",
        "4.8",
        0,
        {
          img: "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
          redirection_url: "",
        },
        {},
        "0",
        1,
        {
          did: "022PXX22.XX22.190118195026.M7Y1",
          cmp_params: {
            bcity: "Mumbai",
            barea: "Andheri East",
            bpncdbd: "400069",
            paidstatus: "1",
            misc: "2097156",
            ask_mobile: 1,
          },
        },
        "Fmc6ep3Y4c%2B1yindNZuEUncO2tkJz2SpHb2gsOaeVY0%3D",
        0,
        "Mumbai/Turquoise-Advisory-Near-Vishal-Hall-Andheri-East/022PXX22-XX22-190118195026-M7Y1_BZDET",
        "",
        ["Business Loans", "Home Loans"],
        [
          {
            tag_name: "Trending",
            bg_colour: "#5271dd",
            txt_colour: "#FFFFFF",
            tag_image:
              "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/trending.svg",
          },
        ],
        "",
        [],
        {},
        [],
        {
          lead: "11",
          lead_resp: "0",
          avg_resp_time_sec: "",
        },
        "400069",
        "",
        {
          cname: "Turquoise Advisory",
          docid: "022PXX22.XX22.190118195026.M7Y1",
          rating: "4.8",
          rating_cnt: "3",
          city: "Mumbai",
          dcity: "mumbai",
          area: "Andheri East",
          pin: "400069",
          ds: "0",
          pdg: "V",
          paid: "1",
          jd_verified: "1",
          guarantee: "",
          trust: "0",
          verified: "0",
          pos: 79,
          tag: "Trending",
          cta_name: "",
          call_cta: "2",
          deals: "",
          jd_cash: "",
          isb2b: "0",
          miscellaneous_flag: null,
          distance: "",
          core_distance: 8218.16,
          search_type: "P",
        },
        1,
        "43U66I6YMU2",
        "Mumbai",
      ],
      [
        "022PXX22.XX22.211116135715.E5X2",
        "Star Finance Services",
        "",
        " Wadala Truck Terminal",
        "19.033628",
        "72.879006",
        "1",
        "4.1",
        "1",
        1,
        "0",
        {
          status: '<span class="font14 fw400 color339">Open 24 Hrs</span>',
          timing: "Open 24 Hrs",
        },
        "Wadala Truck Terminal",
        1,
        "Personal Loans, Loans",
        "09972415879",
        "19",
        "",
        "mumbai",
        "https://content.jdmagicbox.com/comp/mumbai/x2/022pxx22.xx22.211116135715.e5x2/catalogue/star-finance-servises-wadala-truck-terminal-mumbai-personal-loans-q3r64fjbax-250.jpg?clr=#2e382e",
        "19",
        0,
        {
          node1: "",
          node2: "",
          node3: [
            '<span class="font14 fw400 color111">15 Years in Business</span>',
            0,
            0,
          ],
          node1color: [],
        },
        {},
        0,
        0,
        [],
        "other",
        "",
        [],
        "",
        "https://content2.jdmagicbox.com/checkin/mumbai/022PXX22.XX22.211116135715.E5X2.jpg",
        "https://www.justdial.com/DT-43WRHDNBBDS",
        1,
        [],
        "",
        80,
        "",
        "",
        "",
        [
          "https://content.jdmagicbox.com/comp/mumbai/x2/022pxx22.xx22.211116135715.e5x2/catalogue/star-finance-servises-wadala-truck-terminal-mumbai-personal-loans-q3r64fjbax.jpg?clr=#2e382e",
          "https://content.jdmagicbox.com/comp/mumbai/x2/022pxx22.xx22.211116135715.e5x2/catalogue/star-finance-servises-wadala-truck-terminal-mumbai-personal-loans-lou16de38n.jpg",
        ],
        [0, 0, 0],
        "2",
        "",
        "Star Finance Services",
        " Wadala Truck Terminal",
        1,
        0,
        {
          id: 10062199,
          nid: 10062199,
          name: "Business Loans",
        },
        "omizO%2Bc91UhDDCelo6h%2BzNm3oc5btZ7kTkNK3v%2Bo%2Fsc%3D",
        "4.1",
        0,
        {
          img: "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/newprot/ctlgjdpay2x.png",
          redirection_url: "",
        },
        {},
        "0",
        1,
        {
          did: "022PXX22.XX22.211116135715.E5X2",
          cmp_params: {
            bcity: "Mumbai",
            barea: "Wadala Truck Terminal",
            bpncdbd: "400037",
            paidstatus: "1",
            misc: "8589950980",
            ask_mobile: 0,
          },
        },
        "XB2K%2FWHxkD%2Fa%2F%2B57l9n%2BpVB0xJyhf0bcNhHtDJEBM3w%3D",
        0,
        "Mumbai/Star-Finance-Services-Wadala-Truck-Terminal/022PXX22-XX22-211116135715-E5X2_BZDET",
        "",
        ["Personal Loans", "Two Wheeler Loans"],
        [
          {
            tag_name: "Trending",
            bg_colour: "#5271dd",
            txt_colour: "#FFFFFF",
            tag_image:
              "https://akam.cdn.jdmagicbox.com/images/icontent/newwap/web2022/trending.svg",
          },
        ],
        "",
        [],
        {},
        [],
        {
          lead: "645",
          lead_resp: "8",
          avg_resp_time_sec: "",
          tformat: "",
          color: "#339D3A",
        },
        "400037",
        "",
        {
          cname: "Star Finance Services",
          docid: "022PXX22.XX22.211116135715.E5X2",
          rating: "4.1",
          rating_cnt: "19",
          city: "Mumbai",
          dcity: "mumbai",
          area: "Wadala Truck Terminal",
          pin: "400037",
          ds: "0",
          pdg: "",
          paid: "1",
          jd_verified: "1",
          guarantee: "",
          trust: "0",
          verified: "0",
          pos: 80,
          tag: "Trending",
          cta_name: "",
          call_cta: "3",
          deals: "",
          jd_cash: "",
          isb2b: "0",
          miscellaneous_flag: null,
          distance: "",
          core_distance: 8220,
          search_type: "P",
        },
        1,
        "43WRHDNBBDS",
        "Mumbai",
      ],
    ],
    rvs: [],
    bd_route: [],
  },
  nearmeDetails: "",
  catid: "",
  trending_flag: 0,
  trending_nid: "",
  keyword: "Loan Consultants",
  keywordln: "Loan Consultants",
  ishotel: 0,
  keywordResults: [],
  moreKeywords: "0",
  totalNumberofResults: "1",
  sortingOption: {
    basedon: ["distance", "rating", "popular"],
    sort: "",
    char: "",
    morefilter: {
      mv: "1102",
      mh: "Quick Filters",
      md: "",
      ms: 1,
      d: [
        {
          v: "HR",
          d: "Rated 3.5+",
          f: 1,
          s: 0,
          nc: null,
          n: null,
          e: "6",
        },
        {
          v: "OPEN",
          d: "Open Now",
          f: 1,
          s: 0,
          nc: null,
          n: null,
          e: "10",
        },
      ],
    },
    pricefilter: "",
  },
  ratingsTab: 0,
  pncdbd: "",
  ismovie: "0",
  sort_price_tag: null,
  advanced_bd_flag: "0",
  sort_price: null,
  filter_flag: "0",
  image_path: "",
  view: "0",
  national_catid: "10800882",
  median_latitude: "",
  median_longitude: "",
  seo_dt: {
    title: "Top Loan Consultants in Mumbai - Best near me - Justdial",
    desc: "Top Loan Consultants in Mumbai. Find ✓Loans, ✓Business Loans, ✓Home Loans, ✓Personal Loans, ✓Insurance Agents in Mumbai. Get Phone Numbers, Address, Reviews, Photos, Maps , FAQs for top Loan Consultants near me in Mumbai on Justdial.",
    key: "List of Loan Consultants in Mumbai, Reviews, Map, Address, Phone Number, Contact Number, local, popular Loan Consultants, Loan Consultants",
    isfreetext: 0,
    hot_cat_arr: {
      id: 10359572,
      nid: 10359572,
      name: "Personal Loans",
    },
    area: null,
    link: "https://www.justdial.com/Mumbai/Loan-Consultants/nct-10800882",
  },
  vpfs: "",
  msgpos: "",
  areadocids: "",
  area_docids_cnt: "",
  nofriends: "",
  nextdocid: "",
  nextdocidcount: "10",
  scity: "",
  pcity: "mumbai",
  spincode: "",
  amp: null,
  cat_search_type: "L",
  area_docid_count_hotel: "",
  area_last_docid_hotel: "",
  adword_pos: [],
  adword_snippet: [],
  footer: 0,
  adword_docids: "",
  newadd: "Ad",
  newaddcolor: "#ffffff",
  newaddtextcolor: "#000000",
  viewchange: [0],
  view_flag: null,
  dsmap: 1,
  vertical_banner: {},
  srf: "11",
  pharmacy_data: {},
  not_rateable: 0,
  brndname: "Loan Consultants",
  mncatnm: "Loan Consultants",
  comp_avg_starjd: "|$|0",
  lng: "",
  h1: "Top Loan Consultants in Mumbai",
  nrin: " in ",
  microdata: "",
  ldJson: {
    default:
      '{"@context": "http://schema.org","@type": "WebSite","name": "Justdial","url": "https://www.justdial.com/"}',
    rating: "",
    social:
      '[{"@context":"http:\\/\\/schema.org","@type":"Organization","name":"justdial.com","url":"https:\\/\\/www.justdial.com\\/","logo":"https:\\/\\/akam.cdn.jdmagicbox.com\\/images\\/icontent\\/jdrwd\\/jdlogosvg.svg","sameAs":["https:\\/\\/www.facebook.com\\/JustDial","https:\\/\\/plus.google.com\\/+justdial","https:\\/\\/www.linkedin.com\\/company\\/justdial","https:\\/\\/www.instagram.com\\/jd_justdial","https:\\/\\/play.google.com\\/store\\/apps\\/details?id=com.justdial.search","https:\\/\\/itunes.apple.com\\/app\\/jd-justdial\\/id624946027?uo=5","https:\\/\\/www.youtube.com\\/user\\/justdialind"]},{"@context":"http:\\/\\/schema.org","@type":"LocalBusiness","name":"Green Door","image":"https:\\/\\/content.jdmagicbox.com\\/comp\\/def_content\\/business_loans\\/default-business-loans-2.jpg?clr=#403326","address":{"@type":"PostalAddress","streetAddress":"Ghodbunder Road","addresslocality":"Kavesar","addressRegion":"Mumbai","postalCode":"400615","addressCountry":"IN"},"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Green-Door-Near-Vijay-Garden-Kavesar\\/022PXX22-XX22-220423144643-B6K4_BZDET"},{"@context":"http:\\/\\/schema.org","@type":"LocalBusiness","name":"TS Finserv","image":"https:\\/\\/content.jdmagicbox.com\\/comp\\/mumbai\\/x1\\/022pxx22.xx22.200526220308.d4x1\\/catalogue\\/finance-mandi-kalyan-west-mumbai-personal-loans-pud45vrs26.jpg?clr=#273f27","address":{"@type":"PostalAddress","streetAddress":"Rambaug Main Road","addresslocality":"Kalyan West","addressRegion":"Mumbai","postalCode":"421301","addressCountry":"IN"},"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/TS-Finserv-Near-Balaji-Sweets-Kalyan-West\\/022PXX22-XX22-200526220308-D4X1_BZDET"},{"@context":"http:\\/\\/schema.org","@type":"LocalBusiness","name":"Shubh International","image":"https:\\/\\/content.jdmagicbox.com\\/comp\\/thane\\/p2\\/022pxx22.xx22.180627121634.k6p2\\/catalogue\\/shubh-international-mira-road-thane-mortgage-loans-0c8d15sdl0.jpg?clr=#442d22","address":{"@type":"PostalAddress","streetAddress":"Pleasant Road","addresslocality":"Mira Road East","addressRegion":"Mumbai","postalCode":"401107","addressCountry":"IN"},"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Shubh-International-Near-Mira-Bhayandar-Road-Mira-Road-East\\/022PXX22-XX22-180627121634-K6P2_BZDET"},{"@context":"http:\\/\\/schema.org","@type":"LocalBusiness","name":"Mudrakosh","image":"https:\\/\\/content.jdmagicbox.com\\/def_content\\/personal_loans\\/default-personal-loans-8.jpg?clr=#808080","address":{"@type":"PostalAddress","streetAddress":"Chandarvarkar Lane","addresslocality":"Borivali West","addressRegion":"Mumbai","postalCode":"400092","addressCountry":"IN"},"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Mudrakosh-Behind-Byke-Delote-Borivali-West\\/022PXX22-XX22-120706183613-Y3S8_BZDET"},{"@context":"http:\\/\\/schema.org","@type":"LocalBusiness","name":"Unique Finmart","image":"https:\\/\\/content.jdmagicbox.com\\/comp\\/mumbai\\/i8\\/022pxx22.xx22.130214133028.k4i8\\/catalogue\\/unique-finmart-seawoods-mumbai-personal-loans-4z2gjs7top.jpg?clr=#665200","address":{"@type":"PostalAddress","streetAddress":"Sector-50 Old","addresslocality":"Seawoods","addressRegion":"Mumbai","postalCode":"400706","addressCountry":"IN"},"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Unique-Finmart-Near-Juhi-Green-Tower-Seawoods\\/022PXX22-XX22-130214133028-K4I8_BZDET"},{"@context":"http:\\/\\/schema.org","@type":"LocalBusiness","name":"Simran Business Loan","image":"https:\\/\\/content.jdmagicbox.com\\/comp\\/def_content\\/business_loans\\/default-business-loans-0.jpg?clr=#29293d","address":{"@type":"PostalAddress","streetAddress":"Baji Prabhu Deshpande Marg","addresslocality":"Vile Parle West","addressRegion":"Mumbai","postalCode":"400056","addressCountry":"IN"},"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Simran-Business-Loan-Old-Kapol-Bank-Vile-Parle-West\\/022PXX22-XX22-161109112749-H5P2_BZDET"},{"@context":"http:\\/\\/schema.org","@type":"LocalBusiness","name":"Ace Financial Solutions","image":"https:\\/\\/content.jdmagicbox.com\\/comp\\/mumbai\\/l2\\/022pxx22.xx22.230121021513.q8l2\\/catalogue\\/ace-financial-solutions-mumbai-finance-consultants-gc0urcrrbw.jpg","address":{"@type":"PostalAddress","streetAddress":"Ambadi Road","addresslocality":"Vasai West","addressRegion":"Mumbai","postalCode":"401202","addressCountry":"IN"},"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Ace-Financial-Solutions-Opp-Jain-Mandir-and-Behind-Jain-Cosmos-Bnk-Vasai-West\\/022PXX22-XX22-230121021513-Q8L2_BZDET"},{"@context":"http:\\/\\/schema.org","@type":"LocalBusiness","name":"Mangal Credit And Fincorp Ltd","image":"https:\\/\\/content.jdmagicbox.com\\/comp\\/mumbai\\/w4\\/022pxx22.xx22.200915124306.j4w4\\/catalogue\\/mangal-credit-and-fincorp-ltd-goregaon-east-mumbai-personal-loans-b9deegbvy6.jpg?clr=#4f3317","address":{"@type":"PostalAddress","streetAddress":"Ram Mandir Road","addresslocality":"Goregaon East","addressRegion":"Mumbai","postalCode":"400063","addressCountry":"IN"},"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Mangal-Credit-And-Fincorp-Ltd-Off-Western-Express-Highway-Goregaon-East\\/022PXX22-XX22-200915124306-J4W4_BZDET"},{"@context":"http:\\/\\/schema.org","@type":"LocalBusiness","name":"Turquoise Advisory","image":"https:\\/\\/content.jdmagicbox.com\\/comp\\/mumbai\\/y1\\/022pxx22.xx22.190118195026.m7y1\\/catalogue\\/turquoise-advisory-andheri-east-mumbai-home-loans-qfzix0i5q4.jpg?clr=#000066","address":{"@type":"PostalAddress","streetAddress":"Andheri Kurla Road","addresslocality":"Andheri East","addressRegion":"Mumbai","postalCode":"400069","addressCountry":"IN"},"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Turquoise-Advisory-Near-Vishal-Hall-Andheri-East\\/022PXX22-XX22-190118195026-M7Y1_BZDET"},{"@context":"http:\\/\\/schema.org","@type":"LocalBusiness","name":"Star Finance Services","image":"https:\\/\\/content.jdmagicbox.com\\/comp\\/mumbai\\/x2\\/022pxx22.xx22.211116135715.e5x2\\/catalogue\\/star-finance-servises-wadala-truck-terminal-mumbai-personal-loans-q3r64fjbax.jpg?clr=#2e382e","address":{"@type":"PostalAddress","addresslocality":"Wadala Truck Terminal","addressRegion":"Mumbai","postalCode":"400037","addressCountry":"IN"},"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Star-Finance-Services-Wadala-Truck-Terminal\\/022PXX22-XX22-211116135715-E5X2_BZDET"}]',
    listing:
      '{"@context": "http://schema.org","@type": "ItemList",\n    \t"itemListElement" :[{"@type":"ListItem","position":1,"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Green-Door-Near-Vijay-Garden-Kavesar\\/022PXX22-XX22-220423144643-B6K4_BZDET"},{"@type":"ListItem","position":2,"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/TS-Finserv-Near-Balaji-Sweets-Kalyan-West\\/022PXX22-XX22-200526220308-D4X1_BZDET"},{"@type":"ListItem","position":3,"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Shubh-International-Near-Mira-Bhayandar-Road-Mira-Road-East\\/022PXX22-XX22-180627121634-K6P2_BZDET"},{"@type":"ListItem","position":4,"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Mudrakosh-Behind-Byke-Delote-Borivali-West\\/022PXX22-XX22-120706183613-Y3S8_BZDET"},{"@type":"ListItem","position":5,"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Unique-Finmart-Near-Juhi-Green-Tower-Seawoods\\/022PXX22-XX22-130214133028-K4I8_BZDET"},{"@type":"ListItem","position":6,"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Simran-Business-Loan-Old-Kapol-Bank-Vile-Parle-West\\/022PXX22-XX22-161109112749-H5P2_BZDET"},{"@type":"ListItem","position":7,"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Ace-Financial-Solutions-Opp-Jain-Mandir-and-Behind-Jain-Cosmos-Bnk-Vasai-West\\/022PXX22-XX22-230121021513-Q8L2_BZDET"},{"@type":"ListItem","position":8,"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Mangal-Credit-And-Fincorp-Ltd-Off-Western-Express-Highway-Goregaon-East\\/022PXX22-XX22-200915124306-J4W4_BZDET"},{"@type":"ListItem","position":9,"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Turquoise-Advisory-Near-Vishal-Hall-Andheri-East\\/022PXX22-XX22-190118195026-M7Y1_BZDET"},{"@type":"ListItem","position":10,"url":"https:\\/\\/www.justdial.com\\/Mumbai\\/Star-Finance-Services-Wadala-Truck-Terminal\\/022PXX22-XX22-211116135715-E5X2_BZDET"}]}',
    brcrum:
      '{"@context":"http:\\/\\/schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"item":{"@id":"https:\\/\\/www.justdial.com\\/Mumbai","name":"Mumbai"}},{"@type":"ListItem","position":2,"item":{"@id":"https:\\/\\/www.justdial.com\\/Mumbai\\/Loan-Consultants\\/nct-10800882","name":"Loan Consultants in Mumbai"}}]}',
  },
  ttlist: 0,
  footertab: [],
  catessy: {},
  og_tags: {
    type: "company",
    site_name: "Justdial",
    title: "Top Loan Consultants in Mumbai - Best near me - Justdial",
    url: "https://www.justdial.com/Mumbai/Loan-Consultants/nct-10800882",
    description:
      "Top Loan Consultants in Mumbai. Find ✓Loans, ✓Business Loans, ✓Home Loans, ✓Personal Loans, ✓Insurance Agents in Mumbai. Get Phone Numbers, Address, Reviews, Photos, Maps , FAQs for top Loan Consultants near me in Mumbai on Justdial.",
    image: "https://akam.cdn.jdmagicbox.com/images/icontent/jd-logo_nw.png",
    iosurl: "justdial://Mumbai/Loan-Consultants/nct-10800882",
    androidurl:
      "android-app://com.justdial.search/http/t.justdial.com/Mumbai/Loan-Consultants/nct-10800882",
  },
  canonic: "https://www.justdial.com/Mumbai/Loan-Consultants/nct-10800882",
  chainoutlet: 0,
  applink: [],
  number_mask: 0,
  bddisplayText1: "Get the list of best",
  bddisplayText2: null,
  open_abd: 0,
  enable_filter: 1,
  dpa: "",
  bd_data: {},
  abd_data: {},
  bestDeal: null,
  bd_text: "",
  bd_text_orig: null,
  resultString: "in Mumbai",
  bd_msgtype: "",
  bd_captiontype: "",
  aka: "",
  newbddesign: "1",
  calltext: "",
  bdtextdata: "",
  bdtextdatali: "",
  paramsText: "&bd7=&magicname=bdgbp",
  deal_pos: "",
  checkin: "2024-03-08",
  checkout: "2024-03-09",
  checkpos: "2",
  dt_params: {
    fromres: "1",
    city: "Mumbai",
    area: "",
    pincode: "",
    catid: "10800882",
    national_catid: "10800882",
    catname: "Loan Consultants",
  },
  bd_params: {
    bd: "1",
    city: "Mumbai",
    area: "",
    pncdbd: "",
    ncatid: "10800882",
    search: "Loan Consultants",
    case: "sms_email",
    frmpg: "lspg",
  },
  data_i_track: [],
  other: 0,
  noarea: null,
  tabs: null,
  stringdetail:
    "Based on,others have rated this,other have rated this,view all,call,message,share,direction,have rated this,your friend,be first among your friends to rate",
  stringdetaileng:
    "Based on,others have rated this,other have rated this,view all,call,message,share,direction,have rated this,your friend,be first among your friends to rate",
  rhs: 0,
  error: {
    status: 1,
    fallbacksearch: "Loan Consultants",
    rstatus: 200,
    rurl: "",
    inapp: 1,
  },
  phpRestime: 91.825927734375,
  search_id: "f6286b87aec2a116d3afaae5c8537c3be85cb4fc97e754cdc488bfbdcf9557b1",
};

const readCsvData = async () => {
  const results: any[] = [];

  const stream = fs
    .createReadStream("data.csv")
    .pipe(parse({ delimiter: ",", from_line: 2 }))
    .on("data", (data) => results.push(data));

  await finished(stream);

  return results;
};

const writeDataToCsv = async (data: any[]) => {
  const ws = fs.createWriteStream("data.csv");

  const columsn = ["name", "number"];
  ws.write(columsn.join(",") + "\n");

  console.log("writing data to csv file >>>>>>>>>>>>>>>>");
  for await (const ele of data) {
    ws.write(ele.join(",") + "\n");
  }
};

const makeCsvDataUnique = async (data: any[]) => {
  const obj: Record<string, any> = {};

  for await (const ele of data) {
    obj[JSON.stringify(ele)] = ele;
  }

  return Object.values(obj);
};

const parseData = async () => {
  const dataToWrite: any[] = [];
  const data = rawData.results.data;

  for await (const ele of data) {
    dataToWrite.push([ele[1], ele[15]]);
  }

  return dataToWrite;
};

const main = async () => {
  console.clear();

  const startTime = performance.now();

  const parsedData = await parseData();
  const csvData = await readCsvData();
  const uniqueData = await makeCsvDataUnique([...csvData, ...parsedData]);
  await writeDataToCsv(uniqueData);

  const endTime = performance.now();
  console.log("Time Taken: ", endTime - startTime, "ms");
  console.log(" >>>>>>>>>>>>>>>> END <<<<<<<<<<<<<<<<<");
};

main();
